version: "3.9"

services:
  sportstream_app:
    container_name: sportstream_app
    image: sportstreamapp:1.0.0
    build: .
    volumes:
      - ./:/app
    ports:
      - "4000:4000"
    environment:
      - DB_URL=postgresql://postgres:postgres@sportstream_db:5432/postgres
    depends_on:
      - sportstream_db
  sportstream_db:
    container_name: sportstream_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
