version: "3.9"

services:
  sportstream_app:
    container_name: sportstream_app
    image: sportstreamapp:1.0.0
    build: .
    volumes:
      - ./:/app
    ports:
      - "4000:4000"
    environment:
      - DB_URL=postgresql://postgres:postgres@host.docker.internal:5432/postgres
